// Smart Icebreakers — deterministic, template-based conversation starters
// built from two users' real overlapping profile data.
//
// NOT a real AI/LLM call — see backend/utils/compatibilityUtils.js's top
// comment (same reasoning: no ANTHROPIC_API_KEY configured anywhere in this
// project) and MOCK_FEATURES.md for the full explanation. Every string this
// module returns is assembled from a fixed template plus a real value pulled
// off one of the two Profile documents passed in — nothing is ever
// generated by a model.
//
// Pure / DB-independent, same standalone-Node-script-testable pattern as
// compatibilityUtils.js. `profileA` is treated as "the caller" (the person
// who will actually send the icebreaker) and `profileB` as "the match
// partner" (who the icebreaker asks about) — wording below is written from
// that perspective ("ask them about...", "they said...").

const MAX_ICEBREAKERS = 6;
const MIN_ICEBREAKERS = 3;

function normalize(value) {
  return typeof value === 'string' ? value.trim().toLowerCase() : '';
}

function sharedValues(listA, listB) {
  if (!Array.isArray(listA) || !Array.isArray(listB)) return [];
  const bSet = new Set(listB.map(normalize));
  const seen = new Set();
  const shared = [];
  for (const raw of listA) {
    const key = normalize(raw);
    if (key && bSet.has(key) && !seen.has(key)) {
      seen.add(key);
      shared.push(raw);
    }
  }
  return shared;
}

function truncate(text, max = 80) {
  if (!text) return '';
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

// Small set of generic-but-decent fallback starters — used only to top up
// the pool when there isn't enough real overlap to personalize from.
// Deliberately NOT "Hi"/"Hello" — the whole point of this feature is giving
// someone a better opener than that.
const GENERIC_FALLBACKS = [
  "What's the best trip you've taken recently?",
  'If you could plan the perfect weekend, what would it look like?',
  "What's a small thing that made you smile this week?",
  "What's on your travel bucket list this year?",
  "What's your go-to comfort food after a long day?",
  'Coffee, chai, or neither — and why?',
];

// Returns a pool of 3-6 icebreaker strings for this pair. The frontend is
// expected to show 1-2 at a time and cycle through the rest locally via its
// own "Generate another" button (see frontend/src/pages/Chat.jsx) rather
// than re-calling this endpoint — the pool is already fully deterministic
// for a given pair of profiles, so there's nothing new a re-call would ever
// return.
function generateIcebreakers(profileA, profileB) {
  if (!profileA || !profileB) {
    return GENERIC_FALLBACKS.slice(0, MIN_ICEBREAKERS);
  }

  const personalized = [];

  const sharedInterests = sharedValues(profileA.interests, profileB.interests);
  sharedInterests.slice(0, 2).forEach((interest) => {
    personalized.push(`You both love ${interest} — ask them about it!`);
  });

  const promptsA = Array.isArray(profileA.personalityPrompts) ? profileA.personalityPrompts : [];
  const promptsB = Array.isArray(profileB.personalityPrompts) ? profileB.personalityPrompts : [];
  const promptsATexts = new Set(promptsA.map((p) => normalize(p && p.prompt)));
  promptsB
    .filter((p) => p && p.answer && promptsATexts.has(normalize(p.prompt)))
    .slice(0, 2)
    .forEach((p) => {
      personalized.push(
        `You're both into "${p.prompt}" — they said "${truncate(p.answer)}". Share your take!`
      );
    });

  if (
    profileA.datingIntention &&
    profileB.datingIntention &&
    profileA.datingIntention === profileB.datingIntention
  ) {
    personalized.push("You're both looking for the same thing — ask what that means to them.");
  }

  if (profileA.city && profileB.city && normalize(profileA.city) === normalize(profileB.city)) {
    personalized.push(`You're both in ${profileB.city} — ask for their favorite local spot!`);
  }

  const sharedLanguages = sharedValues(profileA.languages, profileB.languages);
  if (sharedLanguages.length > 0) {
    personalized.push(`You both speak ${sharedLanguages[0]} — try greeting them in it!`);
  }

  const dietB = profileB.lifestyle && profileB.lifestyle.diet;
  const dietA = profileA.lifestyle && profileA.lifestyle.diet;
  if (dietA && dietB && dietA === dietB) {
    personalized.push(`You're both ${dietB.replace('_', '-')} — swap favorite spots to eat!`);
  }

  // De-dupe (two different overlaps could in theory produce identical text)
  // while preserving the order they were generated in.
  const deduped = [...new Set(personalized)];
  const pool = deduped.slice(0, MAX_ICEBREAKERS);

  if (pool.length < MIN_ICEBREAKERS) {
    for (const fallback of GENERIC_FALLBACKS) {
      if (pool.length >= MIN_ICEBREAKERS) break;
      if (!pool.includes(fallback)) pool.push(fallback);
    }
  }

  return pool;
}

module.exports = { generateIcebreakers, GENERIC_FALLBACKS, MIN_ICEBREAKERS, MAX_ICEBREAKERS };
